Feat/create list command
mathieurobert1/MyTeams pull request #64
Opened 2024-04-11 17:36 UTC by Njord201

2024-04-11 18:43 UTC, mathieurobert1 approved these changes
Seems good

2024-04-11 20:20 UTC, theophile-jr approved these changes

2024-04-12 07:06 UTC, mathieurobert1 requested changes

2024-04-12 07:06 UTC, mathieurobert1 commented on server/src/commands/list.c
You don't check if _use_state == NULL if the /use command is not set before /list

2024-04-12 08:49 UTC, theophile-jr approved these changes

2024-04-12 09:15 UTC, mathieurobert1 reviewed
Just an enum to rename

2024-04-12 09:15 UTC, mathieurobert1 commented on shared/include/protocol.h
> +    NOT_CONTEXT = 531,
rename this enum by NO_CONTEXT ! pls

2024-04-12 09:20 UTC, RenardFute commented on server/src/commands/utils/command.c
> +    if (use_value == NONE) {
Could have been a guard close to avoid indenting

2024-04-12 09:20 UTC, RenardFute commented on server/src/commands/utils/list_instance.c
> +    int size = 0;
this shall be a size_t since strlen return's size_t

2024-04-12 09:20 UTC, RenardFute commented on server/src/commands/utils/list_instance.c
> +        strcat(str, ", ");
you should take a look at https://man7.org/linux/man-pages/man3/asprintf.3.html

2024-04-12 09:47 UTC, mathieurobert1 approved these changes

2024-04-12 09:56 UTC, merged